config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :budget_types, excpt: [:update, :edit] do 
    resources :budget_affairs, except: [:update, :edit]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    return unless user.present?

    can :manage, BudgetType, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget_affair.rb
class BudgetAffair < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :budget_types, through: :type_affairs, dependent: :destroy
  has_many :type_affairs, dependent: :destroy

  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
  attribute :budget_type_id, :integer
end

app/models/budget_type.rb
class BudgetType < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :type_affairs, dependent: :destroy
  has_many :budget_affairs, through: :type_affairs, dependent: :destroy
  validates :name, :icon, presence: true
end

app/models/type_affair.rb
class TypeAffair < ApplicationRecord
  belongs_to :budget_type, class_name: 'BudgetType'
  belongs_to :budget_affair, class_name: 'BudgetAffair'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :budget_types, foreign_key: 'author_id', dependent: :destroy
  has_many :budget_affairs, foreign_key: 'author_id', dependent: :destroy
  validates :email, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/budget_affairs_controller.rb
class BudgetAffairsController < ApplicationController
  def new
    @affair = BudgetAffair.new
  end

  def create
    @affair = BudgetAffair.new(budget_affair_params)
    @affair.author_id = current_user.id

    if @affair.save
      TypeAffair.create(budget_affair: @affair, budget_type_id: params[:budget_affair][:budget_type_id])
      flash[:success] = 'New Payment Affair successfully added'
      redirect_to budget_type_path(params[:budget_affair][:budget_type_id])
    else
      flash[:error] = 'Error: new payment affair could not be added'
      render :new
    end
  end

  private

  def budget_affair_params
    params.require(:budget_affair).permit(:name, :amount, :budget_type_id)
  end
end

app/controllers/budget_types_controller.rb
class BudgetTypesController < ApplicationController
  before_action :authenticate_user!

  def index
    @budget_types = current_user.budget_types
  end

  def show
    @budget_type = BudgetType.find(params[:id])
    @total = @budget_type.budget_affairs.sum(:amount)
    @affairs = @budget_type.budget_affairs.order(created_at: :desc)
  end

  def new
    @budget_type = BudgetType.new
  end

  def create
    @budget_type = BudgetType.new(budget_type_params)
    @budget_type.author_id = current_user.id
    if @budget_type.save
      flash[:success] = 'New Budget Type added succesfully'
      redirect_to budget_types_path
    else
      flash[:error] = 'Error: New budget type could not be add'
      render :new
    end
  end

  def destroy
    @budget_type = BudgetType.find(params[:id])
    @budget_type.destroy
    flash[:notice] = 'Budget Type removed succesfully'
    redirect_back(fallback_location: budget_types_path)
  end

  private

  def budget_type_params
    params.require(:budget_type).permit(:name, :icon)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budget_affairs_helper.rb
module BudgetAffairsHelper
end

app/helpers/budget_types_helper.rb
module BudgetTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/budget_affairs/new.html.erb
<section class='container'>
  <nav class="navbar bg-light">
    <div class="container-fluid">
      <form class="d-flex">
        <button class="btn btn-outline-success btn-primary me-2" type="button">
          <%= link_to 'Back Budget Type', budget_type_path(params[:budget_type_id]), class: "text-decoration-none text-white" %>
        </button>
      </form>
      <p class="navbar-brand d-flex">New Budget Affairs</p>
    </div>
  </nav>
  <h1 class="display-5 border-bottom padding py-5">Add New Budget Type of Affairs</h1>
  <%= form_with model: @affair, url: budget_type_budget_affairs_path(params[:budget_type_id]), method: :post, local: false, scope: :budget_affair do |form| %>
    <%= form.label :budget_type_id, "Select Category", class: "form-label mt-3" %>
    <%= form.select :budget_type_id, current_user.budget_types.all.map { |type| [type.name, type.id] }, {}, class: "form-control" %>

    <%= form.label :name, class: "form-label mt-3" %>
    <%= form.text_field :name, class: "form-control" %>

    <%= form.label :amount, class: "form-label mt-3" %>
    <%= form.number_field :amount, class: "form-control" %>

    <%= form.submit "Add", class: "btn btn-success btn-lg mt-3 container-md" %>
  <% end %>
</section>

app/views/budget_types/index.html.erb
<section class='container'>
  <h1 class="display-1 border-bottom padding pb-5">Budget Types</h1>
  <%if @budget_types.length.zero? %>
    <p>Add Type of Budget plans</p>
  <% else %>
    <div class="d-grid gap-3">
      <% @budget_types.each do |type| %>
        <div class="p-2 bg-light border">
          <dl class="row">
            <dt class="col-sm-3">
              <%= link_to type.icon, budget_type_path(type.id), class: "text-uppercase text-decoration-none" %>
            </dt>
            <dd class="col-sm-9">
              <h2 class="border-bottom"><%= link_to type.name, budget_type_path(type.id), class: "text-uppercase text-decoration-none" %></h2>
              <p>Total Spent: <%= type.budget_affairs.sum{|bf| bf[:amount]} %></p>
              <% if current_user.present? && can?(:destroy, type) %>
                <%= button_to "Remove", budget_type_path(type.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm ml-2' %>
              <% end %>
            </dd>
          </dl>
        </div>
      <%end%>
    </div>
  <% end %>
  <div class="card-header d-flex justify-content-between align-items-center">
    <button class=" btn btn-primary btn-blue-col btn-lg mt-5">
      <%= link_to 'Add Budget Type', new_budget_type_path, class: "text-decoration-none text-white" %>
    </button>
  </div>
</section>

app/views/budget_types/new.html.erb
<section class='container'>
  <nav class="navbar bg-light">
    <div class="container-fluid">
      <form class="d-flex" >
        <button class="btn btn-outline-success btn-primary me-2" type="button">
          <%= link_to 'Back Budget Type', budget_types_path, class: "text-decoration-none text-white" %>
        </button>
      </form>
      <p class="navbar-brand d-flex">New Budget Type</p>
    </div>
  </nav>
  <h1 class="display-5 border-bottom padding py-5">Add New Budget Type</h1>
  <%= form_with model: @budget_type do |form| %>

    <%= form.label :name, class:"form-label mt-3" %>
    <%= form.text_field :name, class:"form-control" %>
    
    
    <%= form.label :icon, class:"form-label mt-3" %>
    <%= form.text_field :icon, class:"form-control", id: "category_icon" %>
      
    <%= form.submit "Create", class: 'container-md btn btn-success btn-lg mt-3' %>

  <% end %>
</section>

app/views/budget_types/show.html.erb
<section class='container'>
  <nav class="navbar bg-light">
    <div class="container-fluid">
      <form class="d-flex" >
        <button class="btn btn-outline-success btn-primary me-2" type="button">
          <%= link_to 'Back Budget Type', budget_types_path, class: "text-decoration-none text-white" %>
        </button>
      </form>
      <p class="navbar-brand d-flex">Budget Type:- <%= @budget_type.name %> </p>
    </div>
  </nav>
  <h3 class="display-5 border-bottom padding py-5">Total `<%= @budget_type.name %>` Affairs <%= "Expenses: $#{@total}" %> </h3>
    <div class="d-grid gap-3">
      <% @affairs.each do |affair| %>
        <div class="p-2 bg-light border">
          <dl class="row">
            <dt class="col-sm-3 text-uppercase text-decoration-none">
              <%= @budget_type.name %>
            </dt>
            <dd class="col-sm-9">
              <h2 class="border-bottom text-uppercase text-decoration-none">
                <%=  affair.name %>
              </h2>
              <p>Total Spent: <%= "$#{affair.amount}" %>.</p>
            </dd>
          </dl>
        </div>
      <%end %>
    </div>
  <div class="card-header d-flex justify-content-between align-items-center">
    <button class=" btn btn-primary btn-blue-col btn-lg mt-5">
      <%= link_to 'Add New Budget Affair', new_budget_type_budget_affair_path(params[:id]), class: "text-decoration-none text-white" %>
    </button>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="container py-3 my-4">
  <p class="text-center text-muted border-top">© 2023 Company, Inc</p>
</footer>

app/views/layouts/_header.html.erb
<header class="container">
  <nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Budget App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Budget App</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <%= link_to 'Budget Types', budget_types_path, class: 'nav-link' %>
            </li>
            <% if current_user.present? %>
            <li class="nav-item">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %>
            </li>
            <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/index.html.erb
<section class='text-center'>
  <h3>Welcome to Budget app</h3>
  <% if current_user.present? %>
    <h4><%= current_user.name %></h4>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %>
    <div class='budget_view'>
      <%= link_to 'View Your Budget Plans', budget_types_path,class: 'btn btn-primary mr-2' %>
    </div>
  <% else %>
    <div class="ml-auto ">
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary mr-2' %>
      <%= link_to 'Sign-up', new_user_registration_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</section>